### ISSUE TITLE
Stream plans to matsim xml

### ISSUE THREAD

**Issue by fredshone** [arup-group/pam#164]
Would be useful to stream matsim plans to xml (we have read stream already).

Would be great for reducing memory requirement for simpler ops especially via cli

**Comment by markusstraub** [comment]
Are you interested in a pull request regarding this feature? (I would also propose dropping matsim v11 support)

**Comment by fredshone** [comment]
for sure 🙏🏻  , and yes happy to drop v11 now.

I think a lot of the functionality already in `write.matsim`, [eg](https://github.com/arup-group/pam/blob/f03d7956bf411cd3e79b0e11b0dc9ba003cd8308/pam/write/matsim.py#L128), including some xml type hacks that need to be preserved.

for context, we'd like to support some simple person level ops via the cli, such as:

```
with pam.write.matsim.FancyNewXMLStreamingWrapper(OUT, etc) as f:
    for person in pam.read.stream_matsim_persons(PATH, etc):
        pam.samplers.time.apply_jitter_to_plan(person.plan, etc)
        f.write(person)
```

Not sure `FancyNewXMLStreamingWrapper` is really required, but it would be nice to ensure that the `<population>` element is ultimately closed. Let me know your thoughts (just thinking out loud) :)
