### ISSUE TITLE
Cleaning up unused scripts outside the source code directory

### ISSUE THREAD

**Issue by brynpickering** [arup-group/pam#194]
There is a script that hasn't been touched in 3 years, since it was introduced in #28: [trip_synthesiser.py](https://github.com/arup-group/pam/blob/main/scripts/data-synthesis/trip_synthesiser.py). 

Does this still serve a purpose @mfitz? I can't see a reference to it in any other `arup-group` projects, but maybe it is used in production somewhere? If so, it should move to the core code.

If not, then I can kill the scripts subdir in #193 🎉

**Comment by mfitz** [comment]
Can't remember a thing about that one, @brynpickering, so I think we can kill it 👍

**Comment by brynpickering** [comment]
@fredshone the same question to you about `bin/quick_stats.py`. You introduced that in [this commit](https://github.com/arup-group/pam/commit/0c63d84315118899b62d6ec2d7edb990ca574461).

**Comment by fredshone** [comment]
> @fredshone the same question to you about `bin/quick_stats.py`. You introduced that in [this commit](https://github.com/arup-group/pam/commit/0c63d84315118899b62d6ec2d7edb990ca574461).

burn it all

**Comment by brynpickering** [comment]
Fixed by #199
