### ISSUE TITLE
Docker container entry point should be `python` not `ipython`

### ISSUE THREAD

**Issue by brynpickering** [arup-group/pam#228]
### What happened?

I tried using the generated PAM Docker image to run a job on AWS and realised that the entry point for the container should not be `ipython`, but rather `python`. I initially set the entry point to `ipython` as I assumed most people would interact with the container interactively, but that was probably only true when installing PAM on Windows devices was a massive pain. Now, most people are going to run python scripts as commands on the Docker container from an e.g. AWS job, so `python` makes more sense.

In the meantime, it is possible to get the same result as `python -m my_script ....` by calling `ipython -- my_script ....`

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

### Version

0.2.5-dev

**Comment by Theodore-Chatziioannou** [comment]
> @Theodore-Chatziioannou how do you use PAM on AWS workboxes? Always using python scripts or using the PAM CLI?

both. Usually scripts for more complex tasks (ie creating a new population), and the CLI for simple tasks (such as combining household and freight populations).

**Comment by brynpickering** [comment]
so maybe the docker container entry point should be plain bash? Then you can use the CLI `pam ...` and invoke python scripts `python -m ...`?
