### ISSUE TITLE
save a facility sampler

### ISSUE THREAD

**Issue by akay-arup** [arup-group/pam#67]
FSs take a while to build, so may be good to be able to create a way to save a pre-baked FS and then importing it into a synthesis pipeline. Currently `FacilitySampler ` class is a generator, which can't be pickled. Consider adding a FacilitySampler.dump() and .load() methods?

**Comment by Theodore-Chatziioannou** [comment]
added export/load functionality

**Comment by akay-arup** [comment]
Missed the boat on closing, but have been testing this today. So far, it seems to save about a minute compared to building from scratch but a large % change. Build from scratch ~200+ seconds, build from pickle ~110 seconds.
