### ISSUE TITLE
facility sampler behavior problems

### ISSUE THREAD

**Issue by akay-arup** [arup-group/pam#85]
Using a FacilitySampler via `Population.sample_locs` fails to return point locations with repeated warnings that look like
```
Using random sample for zone:252:home
Cannot find idx:252, returning None
Using random sample for zone:262:shop_food
Using random sample for zone:262:shop_food
Using random sample for zone:258:shop_food
Using random sample for zone:258:home
Cannot find idx:258, returning None
....
```
However, tests using the same sampler yield valid shapely points:

- `facility_sampler.sample('258', 'shop_food')` yields a valid shapely point, with `Using random sample ...` warning.
- `facility_sampler.sample('258', 'home')` yields a valid shapely point, without warning.

FacilitySampler params are set to `fail=False, random_default=True` with the input zones having the zone id as index. 

The `returning None` error traces back to the `spatial.RandomPointSampler` class (see below) -- my best guess is there is a problem with the way the idxs are being passed around the various facility sampling methods in core, facility, and spatial modules.
https://github.com/arup-group/pam/blob/663f49d36b1c8533d44a6d71582b697eeee91d7f/pam/samplers/spatial.py#L42-L46

**Comment by fredshone** [comment]
Thanks for raising this. My first thought is that `Cannot find idx:258, returning None` is simply raised when the idx is not found. I see that you have tested this, but is it possible that the type is wrong (either in the sampler or population location), ie `str` vs `int`?

The random sampler kicks in when an idx is found for a zone - but there are no facilities of the requested type. In this case the area is known but not the viable points, so a random point within the area is returned.

I need to check this more carefully - there have been some changed to the sampler.

I think we should add a validation of diagnostic method to check that the facility sampler is valid for a given set of ids and activity types.

**Comment by akay-arup** [comment]
Ah -- yes. It is a dtype issue.

I had checked the zone id's  input `trips`, `households`, and `zones` files were all `str` -- however, the the home zones of the input `people` were given as `int` -- utlimately resulting in a mix of `str` and `int` for `person.activity.location.area`
