### ISSUE TITLE
Redesign notebooks directory

### ISSUE THREAD

**Issue by fredshone** [arup-group/pam#93]
There are a growing number of notebooks in the "notebooks" directory.

Use of these notebooks should be better designed streamlined, specifically:
- rename as "examples" directory
- maybe provide a README.md document in the notebooks dir, providing contents and summaries 
- give notebooks some sensible ordering and prefix names so they are shown in correct order. Additional change names so that style if consistent
- generally improve consistency across notebooks
- ensure that major use cases are covered with a focus on new users

**Comment by JosePazNoguera** [comment]
This is now done
