### ISSUE TITLE
Consolidate pam.write tabular methods

### ISSUE THREAD

**Issue by fredshone** [arup-group/pam#96]
There are a number of tabular write methods in pam.write:
- write_travel_diary
- dump (wrap of to_csv)
- to_csv (this is the dominant method, also used by pam.core.Population.to_csv)
- write_population_csv (this function is similar to above but can write multiple populations - originally used to create a "database" of tables for PowerBI)

Requirements:
- consolidate into single function/method
- remove code duplication
- simplify user interface/update docs
- fix breaking changes to example notebooks

Additionally it would be great to provide consistency as much as possible with column names in the elara log outputs (https://github.com/arup-group/elara/blob/6755d4d27866463466e15a9abac316f3951d7e6f/elara/plan_handlers.py#L662). The idea to make these two outputs (pre and post sim) more easilly comparable.

**Comment by JosePazNoguera** [comment]
This is now done
